import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { useQuery, gql } from '@apollo/client'
import { useEffect } from 'react'
import DisplayArea from '@/components/displayArea'


const FACEBOOK_REPOS = gql`
  query getFacebookRepos {
    organization(login: "facebook") {
      repositories(first: 12, orderBy: {field: UPDATED_AT, direction: DESC}) {
        edges {
          node {
            id
            description
            name
            url
          }
        }
      }
    }
  }
`

export default function Home() {
  const { loading, error, data } = useQuery(FACEBOOK_REPOS)

  useEffect(() => {
    console.log(data)
  }, [])

  return (
    <>
      <Head>
        <title>App Repo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1> facebook repositories </h1>
        { error ? 'Error' : loading ? 'Loading...' : <DisplayArea apiResponse={data} /> }
      </main>
    </>
  )
}
