import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { useQuery, gql } from '@apollo/client'

const FACEBOOK_REPOS = gql`
  query getFacebookRepos {
      user(login: "Meta") {
        id
        repositories(last: 10, orderBy: {field: CREATED_AT, direction: DESC}) {
          nodes {
            description
            id
            name
            url
            createdAt
            updatedAt
          }
        }
      }
    }
`

export default function Home() {
  const { loading, error, data } = useQuery(FACEBOOK_REPOS)
  console.log("data : ", data)

  return (
    <>
      <Head>
        <title>App Repo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1> facebook repositories </h1>
      </main>
    </>
  )
}
